### ISSUE TITLE
Cannot use with { enforceActions: "always" } - "Since strict-mode is enabled, changing observed observable values outside actions is not allowed."

### ISSUE THREAD

**Issue by acoutts** [aihornmac/mobx-localstorage#2]
The issue is that when MobX is configured to always enforce actions, this library does not respect the pattern that all observable properties can only be modified with a function decorated as an action.

The main issue is in the constructor in the call `super.set()` and `super.delete()`:
```typescript
constructor() {
    super(undefined, referenceEnhancer, 'LocalStorage')
    const len = localStorage.length
    for (let i = 0; i < len; i++) {
      const key = localStorage.key(i)!
      const value = parseValue(localStorage.getItem(key))
      super.set(key, value)
    }
    localStorage.on('change', (key, value) => {
      if (typeof value === 'string') {
        super.set(key, parseValue(value))
      } else {
        super.delete(key)
      }
    })
  }
```

Also, the class functions for setting / removing keys should probably also be decorated as actions to be safe.

**Comment by aihornmac** [comment]
@acoutts Thx for the heads-up! I totally missed this part since I have never enabled this option in my projects. Fixed in 1.1.1, please upgrade to test. I am closing this issue, should there be any problem, feel free to reopen it.
