### ISSUE TITLE
Strings saved to localstorage have quotes

### ISSUE THREAD

**Issue by uraz** [aihornmac/mobx-localstorage#4]
Is there any reason why strings saved into localstorage are in quotes `"string"`?

**Comment by aihornmac** [comment]
@uraz It was designed to parse and store JSON, so string is stringified with `JSON.stringify`

**Comment by uraz** [comment]
Would you consider adding additional check if passed value is a valid JSON or plain string?

**Comment by aihornmac** [comment]
@uraz I think it's impossible to distinguish JSON from plain text, since you can pass a string whose content is actually JSON. Although when it fails to parse JSON, it returns the value as plain text. I guess what you might want is to treat every value as plain text and don't need `mobx-localstorage` to do any parsing for you (or alternative parser you specify). Can you confirm the actual demand?

**Comment by uraz** [comment]
Actually all I want is to observe a single value in localstorage

**Comment by aihornmac** [comment]
@uraz if `mobx` is not an absolute requirement, you might want to give `reactive-localstorage` a try.

**Comment by uraz** [comment]
I've already used `mobx-localstorage` and it's working as supposed. I was just wondering if `JSON.stringify(toJS(value))` is a must. If someone wants to save JSON he/she can give a parsed/stringified argument to `setItem`

**Comment by aihornmac** [comment]
@uraz That was exactly what my last long answer proposed. It might be fulfilling to let user configure parsing behavior for themselves. Is this what you actually want?

**Comment by aihornmac** [comment]
@uraz The reason why it automatically treat everything as JSON was a historical issue. If current behavior is altered to not parsing, it should be a breaking change. So adding a configure might help the case without requiring projects in action to pay the extra efforts.

**Comment by uraz** [comment]
> [...] It might be fulfilling to let user configure parsing behavior for themselves. Is this what you actually want?

Yes it would be sufficient :)

**Comment by aihornmac** [comment]
@uraz `v1.2.0` should solve your problem. Please give it a try. Should there be any problem, feel free to reopen this issue.
